import type { HhGenreId } from "./genres";

/**
 * Fifty reference tracks per lane: artist, title, year, BPM, what to learn
 * from it. Assembled from memory as a listening list — years and BPMs are
 * approximate and the UI lets you edit or add your own. Nothing here is
 * audio; the analyser compares against the lane profile in `genres.ts`,
 * then points you at the closest references by tempo.
 */
export type RefTrack = {
  id: string;
  genre: HhGenreId;
  artist: string;
  title: string;
  year: number;
  bpm: number;
  note: string;
};

type Row = [artist: string, title: string, year: number, bpm: number, note: string];

const slug = (s: string) =>
  s
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

function lane(genre: HhGenreId, rows: Row[]): RefTrack[] {
  return rows.map(([artist, title, year, bpm, note]) => ({
    id: `${genre}-${slug(artist)}-${slug(title)}`,
    genre,
    artist,
    title,
    year,
    bpm,
    note,
  }));
}

const EARLY: Row[] = [
  ["DJ Zany", "Sky High", 2002, 140, "The reverse-bass blueprint: dry kick, swell into the beat."],
  ["Deepack", "The Prophecy", 2003, 145, "Screech-as-hook, tribal toms, sampled vocal."],
  ["Hardheadz", "Hardhouz Generation", 2003, 142, "Hard house DNA, off-beat bass groove."],
  ["Hardheadz", "Wreck Thiz Place", 2003, 143, "Shouted vocal over a tight kick/reverse pattern."],
  ["The Beholder & Balistic", "Decibel", 2003, 145, "Anthem structure done with almost no melody."],
  ["Blutonium Boy", "Hardstyle Instructor", 2003, 144, "German take: harder kick, longer break."],
  ["DJ Isaac", "Nobody Listens to Techno", 2004, 146, "Vocal hook + reverse bass, pure club tool."],
  ["Deepack", "Stampede", 2004, 146, "Tribal percussion carrying the drop."],
  ["Southstylers", "Pounding Senses", 2004, 146, "Showtek alias; punchy kick, pitched screech riff."],
  ["DJ Pavo", "Raverz", 2004, 145, "Classic Dutch groove, minimal harmony."],
  ["DJ Duro", "Cocaine MF", 2005, 146, "Sample-led, off-beat bass drives everything."],
  ["The Prophet", "Big Boys Don't Cry", 2005, 146, "Reverse bass at its loudest, tiny lead motif."],
  ["Technoboy", "Ti Sento", 2005, 148, "Italian school: sung sample, harder kick."],
  ["Technoboy", "Into Deep", 2005, 148, "Screech phrasing that follows the kick rhythm."],
  ["Tatanka", "Afrika", 2005, 146, "Tribal chant hook, tom-heavy break."],
  ["Donkey Rollers", "No One Can Stop Us", 2005, 146, "Anthemic shout, early melodic lead in the break."],
  ["Alpha Twins", "The Darkside", 2005, 148, "Dark reverse-bass groove, pitched-down vocal."],
  ["DJ Isaac", "Impressed", 2005, 147, "Bouncy off-beat, vocal chops as percussion."],
  ["Pavo", "Communicate", 2006, 148, "Reverse bass with a clean sub, spoken hook."],
  ["The Prophet", "Follow the Leader", 2006, 148, "Break builds on a single screech note."],
  ["Deepack", "Drop Out", 2006, 148, "Transitional: tail starts to grow, still reverse bass."],
  ["Showtek", "FTS", 2006, 148, "Shout sample, pitched screech, hard clap."],
  ["Showtek", "Save the Day", 2006, 150, "First hints of the tuned tail and melodic lead."],
  ["Technoboy", "Next Dimensional World", 2006, 148, "Big-room screech riff, Italian kick."],
  ["Technoboy", "Rage", 2006, 148, "Aggressive vocal hook, straight groove."],
  ["Headhunterz", "The Sacrifice", 2006, 150, "Early Headhunterz: reverse bass meets melody."],
  ["Zany", "Pillz", 2007, 148, "Hard, dry kick; the hook is one vocal word."],
  ["Showtek", "Colors of the Harder Styles", 2007, 150, "Spoken intro, screech lead — a genre summary."],
  ["Showtek", "The F-Track", 2007, 150, "Kick and bass do the melodic work."],
  ["Showtek", "Electronic Stereo-phonic", 2007, 150, "Vocal call-and-answer with the reverse bass."],
  ["Showtek", "Partylover", 2007, 150, "Sample hook, sing-along break, dry drop."],
  ["Technoboy", "Catfight", 2007, 149, "Tuned screech riff, the bridge to nu-style."],
  ["Headhunterz", "Forever Az One", 2007, 150, "Melodic lead begins to replace the screech."],
  ["Headhunterz", "Rock Civilization", 2007, 150, "Vocal-driven, longer tail, reverse bass in the mid."],
  ["DJ Isaac", "Bad Dreams", 2007, 150, "Spoken sample break; fat reverse bass."],
  ["DJ Isaac", "Burn", 2007, 150, "Chord stabs on top of an old-school groove."],
  ["Donkey Rollers", "Silver Bullet", 2007, 150, "Reverse-bass drop, melodic break."],
  ["Zany", "Nothing Else", 2005, 147, "Pitched screech with heavy phaser."],
  ["Deepack", "Here Comes the Thunder", 2005, 147, "Tom rolls as the build, no snare roll yet."],
  ["The Prophet", "Recession", 2006, 148, "Reverse bass pushed forward in the mix."],
  ["Luna", "Dance With the Stars", 2006, 147, "Cleaner Dutch groove, small melodic riff."],
  ["Dana", "Every Time", 2005, 146, "Lady Dana's dry, clubby kick."],
  ["Max Enforcer", "Screamin'", 2006, 148, "Screech as the entire drop."],
  ["Dutch Master", "Ghostbusters", 2004, 145, "Sample bootleg era; reverse bass on top."],
  ["Blutonium Boy", "Make It Loud", 2005, 146, "German hardstyle: harder, faster, less melody."],
  ["Tuneboy", "Hardstyle Party", 2005, 147, "Italian party template; vocal + screech."],
  ["Zenith", "Peace of Mind", 2006, 148, "Reverse bass with a one-chord pad."],
  ["Alphaverb", "Music Is My Hobby", 2007, 150, "Late reverse-bass era, melodic break."],
  ["DJ Isaac", "Face Down", 2004, 146, "Off-beat bass, shouted vocal, minimal drop."],
  ["Kutski", "Drowning", 2006, 147, "UK slant on the reverse-bass formula."],
];

const CLASSIC: Row[] = [
  ["Headhunterz", "Subsonic", 2008, 150, "Nu-style formula in one track: melody, climax, tail."],
  ["Headhunterz", "The Power of the Mind", 2008, 150, "Spoken vocal break into a tuned kick drop."],
  ["Headhunterz", "Hate It or Love It", 2008, 150, "Vocal hook + supersaw, 32-bar phrasing."],
  ["Headhunterz & Wildstylez", "Blame It on the Music", 2008, 150, "Climax kick playing the melody."],
  ["Project One", "The Art of Creation", 2008, 150, "The era's manifesto: kick tail as a lead."],
  ["Project One", "Rate Reducer", 2008, 150, "Tail pitch-bend tricks and long breaks."],
  ["Project One", "Life Beyond Earth", 2008, 150, "Pad-led break, tuned drop."],
  ["Wildstylez", "Muzik", 2008, 150, "Screech + melody pairing."],
  ["Noisecontrollers", "Ctrl.Alt.Delete", 2008, 150, "Digital, punchy kick; arpeggiated lead."],
  ["Noisecontrollers", "Marlboro Man", 2008, 150, "Vocal sample chopped into the groove."],
  ["Showtek", "Black 2008", 2008, 150, "Big kick, sample hook, festival phrasing."],
  ["Zatox", "Action", 2008, 150, "Italian kick punch, shout hook."],
  ["Zatox", "Gangsta", 2008, 150, "Reverse bass returns inside a nu-style track."],
  ["D-Block & S-te-Fan", "Music Made Addict", 2008, 150, "Sung vocal break with a tuned drop."],
  ["Showtek", "We Speak Music", 2009, 150, "Simple riff, loud kick, huge break."],
  ["Showtek", "Shout Out", 2009, 150, "Hook is the vocal; drop is kick + one lead."],
  ["Headhunterz", "Scrap Attack", 2009, 150, "Anthem structure: melody teased three times."],
  ["Headhunterz", "Psychedelic", 2009, 150, "Melody carried by the climax kick."],
  ["Noisecontrollers", "Attack Again", 2009, 150, "Aggressive tail, screech counter-riff."],
  ["Noisecontrollers", "Revolution Is Here", 2009, 150, "Filtered lead intro into a full drop."],
  ["Coone", "Starf*ckers", 2009, 150, "Belgian kick, vocal chops, big saw lead."],
  ["Brennan Heart", "Lose My Mind", 2009, 150, "Sung hook with a pluck lead."],
  ["D-Block & S-te-Fan", "Shivers", 2009, 150, "Pitch-bent lead, long emotional break."],
  ["Frontliner", "Weekend Warriors", 2010, 150, "Festival anthem template."],
  ["Frontliner", "Spacetime", 2009, 150, "Arpeggiated lead over a tuned kick."],
  ["Wildstylez", "A Complex Situation", 2010, 150, "Chord-stab drop, spoken vocal."],
  ["Headhunterz & Brennan Heart", "The MF Point of Perfection", 2010, 150, "Two leads trading phrases."],
  ["Headhunterz", "Just Say My Name", 2010, 150, "Vocal break, climax mid-section."],
  ["Brennan Heart", "Musical Impressions", 2010, 150, "Piano break into a saw-lead drop."],
  ["Noisecontrollers", "Shreek", 2010, 150, "Screech-led drop in the nu-style era."],
  ["Noisecontrollers", "Yellow Minute", 2010, 150, "Bouncy tail, arpeggio hook."],
  ["TNT", "Countdown", 2010, 150, "Italian duo: hard kick, vocal countdown."],
  ["Coone", "Music Is Art", 2010, 150, "Vocal-led anthem, D-Block-style chords."],
  ["Coone", "Words From the Gang", 2010, 150, "Sample hook over a bouncy tuned kick."],
  ["Coone & Deepack", "Monstah", 2010, 150, "Screech + kick edits, darker nu-style."],
  ["D-Block & S-te-Fan", "Evolutionz", 2010, 150, "Pluck lead, stacked octaves."],
  ["Ran-D", "Zombie", 2011, 150, "Where nu-style tips into raw: heavier tail."],
  ["Coone", "Nustyle Crap", 2011, 150, "Self-aware nu-style: all the tricks at once."],
  ["Frontliner", "Symbols", 2011, 150, "Anthemic saw lead, choir layer in the break."],
  ["Headhunterz & Noisecontrollers", "Club Bizarre", 2011, 150, "Sample cover with a tuned drop."],
  ["Headhunterz", "From Within", 2011, 150, "Long break, pitched vocal, clean tail."],
  ["JDX", "Live the Moment", 2011, 150, "Sung female vocal, supersaw chorus."],
  ["Code Black", "Brighter Day", 2011, 150, "Australian nu-style: bright lead, big chords."],
  ["Max Enforcer", "Fade to Black", 2011, 150, "Dark piano break, tuned kick."],
  ["TNT", "First Match", 2011, 150, "Bouncy Italian kick, shout hook."],
  ["Brennan Heart & Zatox", "Fight the Resistance", 2012, 150, "Hybrid: nu-style melody, harder kick."],
  ["Wasted Penguinz", "Wistfulness", 2012, 150, "Melancholic lead, soft kick."],
  ["Da Tweekaz", "Wodka", 2012, 150, "Party nu-style: vocal chops, bouncy tail."],
  ["Headhunterz & Wildstylez", "World of Madness", 2012, 150, "Defqon anthem, melody-first drop."],
  ["Headhunterz", "Dragonborn", 2012, 150, "Orchestral break into a clean tuned drop."],
];

const EUPHORIC: Row[] = [
  ["Wildstylez ft. Niels Geusebroek", "Year of Summer", 2013, 150, "Pop topline over a clean kick."],
  ["Headhunterz ft. Malukah", "Reignite", 2013, 150, "Vocal chorus doubled by the lead."],
  ["Headhunterz & Krewella", "United Kids of the World", 2013, 150, "EDM-crossover euphoric."],
  ["Coone", "Into the Madness", 2013, 150, "Chord changes inside the drop."],
  ["Noisecontrollers", "Down Down", 2013, 150, "Vocal chops + pluck lead."],
  ["Noisecontrollers", "E=NC²", 2013, 150, "Layered lead, controlled tail."],
  ["Toneshifterz", "I Am Australian", 2013, 150, "Anthemic chorus melody."],
  ["Wasted Penguinz", "Melancholia", 2013, 150, "Emotional chords, long break."],
  ["Coone", "Survival of the Fittest", 2014, 150, "Festival anthem, choir + supersaw."],
  ["Da Tweekaz", "Tequila", 2014, 150, "Party vocal, bouncy sidechained pad."],
  ["Da Tweekaz", "Frozen", 2014, 150, "Pop cover treatment: verse/chorus map."],
  ["Wildstylez", "Straightforward", 2014, 150, "Pluck lead + sub-heavy kick."],
  ["Noisecontrollers", "All Around the World", 2014, 150, "Vocal hook, bright octave layer."],
  ["Hard Driver", "Lucid Dream", 2014, 150, "Pad-heavy break, clean drop."],
  ["Atmozfears", "Release", 2014, 150, "Sung vocal, layered supersaws."],
  ["Atmozfears & Audiotricz", "What About Us", 2015, 150, "Chorus-first structure."],
  ["Atmozfears ft. David Spekter", "Living for the Future", 2015, 150, "Verse/pre/chorus in hardstyle form."],
  ["Code Black & Atmozfears", "Accelerate", 2015, 150, "Fast pluck arp under a vocal."],
  ["Brennan Heart", "F.I.F.O.", 2015, 150, "Vocal hook, clean tail, big riser build."],
  ["Coone & Da Tweekaz", "D.W.X.", 2015, 150, "Label anthem: stacked leads."],
  ["Da Tweekaz", "Jägermeister", 2015, 150, "Sample hook, sidechain pump."],
  ["Hard Driver", "The Motherland", 2015, 150, "Chord progression carries the drop."],
  ["Coone ft. David Spekter", "Faye", 2016, 150, "Radio-length vocal euphoric."],
  ["Da Tweekaz", "Bring Me to Life", 2016, 150, "Rock cover flipped into euphoric."],
  ["Da Tweekaz", "Komon", 2016, 150, "Vocal chop lead, festival build."],
  ["Atmozfears", "Keep Me Awake", 2016, 150, "Pop chorus, pluck counter-melody."],
  ["Bass Modulators", "Oxygen", 2016, 150, "Bright lead, clean sub under the tail."],
  ["Coone", "The Undefined", 2016, 150, "Layered leads, orchestral break."],
  ["Sound Rush", "Melody of the Night", 2017, 150, "Arpeggio + vocal, polished kick."],
  ["D-Block & S-te-Fan", "Ghost Stories", 2017, 150, "Dark-but-melodic vocal anthem."],
  ["Wildstylez", "Temple of Light", 2017, 150, "Qlimax-scale build and drop."],
  ["Noisecontrollers", "Pillars of Creation", 2017, 150, "Wide, layered, bright lead."],
  ["Da Tweekaz", "Circle of Life", 2018, 150, "Orchestral cover, euphoric drop."],
  ["Headhunterz & Sound Rush", "Rescue Me", 2018, 150, "Vocal chorus, pluck lead."],
  ["D-Block & S-te-Fan", "Twilight Zone", 2018, 150, "Sub-heavy kick, sung hook."],
  ["Sub Zero Project", "Renegades", 2018, 150, "Melodic SZP with psy FX."],
  ["Headhunterz", "Orange Heart", 2019, 150, "Emotional vocal euphoric."],
  ["Headhunterz & Crystal Lake", "Lost", 2019, 150, "Pop structure, layered chorus."],
  ["D-Block & S-te-Fan & Sub Zero Project", "Darkest Hour (The Clock)", 2019, 150, "Vocal hook with a heavy kick."],
  ["Headhunterz", "Home", 2021, 150, "Vocal-first, clean tail, radio edit."],
  ["Brennan Heart ft. Jonathan Mendelsohn", "Imaginary", 2012, 150, "Sung ballad break, tuned drop."],
  ["Wasted Penguinz", "Loneliness", 2012, 150, "Melancholic euphoric blueprint."],
  ["Audiotricz", "Inspiration", 2014, 150, "Bright supersaw, tight kick."],
  ["Demi Kanon", "Ready or Not", 2016, 150, "Vocal chop hook, wide lead."],
  ["Refuzion", "Remember", 2017, 150, "Chord-led drop, vocal chops."],
  ["Adrenalize", "The Groove", 2016, 150, "Pluck-led euphoric groove."],
  ["Devin Wild", "Fight for Something", 2018, 150, "Vocal hook, sub-heavy kick."],
  ["Vertile", "Stardust", 2020, 150, "Modern euphoric: clean, wide, bright."],
  ["Sound Rush", "Made for Tonight", 2019, 150, "Pop chorus over a polished kick."],
  ["Keltek", "Bloodline", 2018, 150, "Layered lead, cinematic break."],
];

const RAW: Row[] = [
  ["Ran-D", "Zombie", 2011, 150, "Proto-raw: heavier tail, dark stabs."],
  ["Digital Punk", "Shock", 2011, 150, "Distorted mids, screech riff."],
  ["Gunz for Hire", "Sorrow", 2012, 150, "Dark chord stabs, mid-heavy kick."],
  ["Gunz for Hire", "Gangsters Don't Dance", 2013, 150, "Sample hook over a gritty kick."],
  ["Gunz for Hire", "No Mercy", 2013, 150, "Kick edits every 8 bars."],
  ["Radical Redemption", "Annihilate", 2014, 150, "Brutal tail, screech stacks."],
  ["E-Force", "Seven", 2013, 150, "Screech-led drop, dark break."],
  ["Warface", "Perfect Weapon", 2013, 150, "Crunchy mid-range kick."],
  ["Warface", "Live for This", 2015, 152, "Shout hook, kick roll transitions."],
  ["Gunz for Hire", "Bolivia", 2015, 152, "Sample-driven, thick tail."],
  ["Radical Redemption", "Command & Conquer", 2016, 152, "Screech as percussion."],
  ["B-Front & Frequencerz", "Psycho", 2016, 152, "Two-chord stab, aggressive kick."],
  ["Ran-D ft. Skits Vicious", "Living for the Moment", 2016, 152, "Rap vocal + raw kick."],
  ["Sub Sonik", "Strike One", 2016, 155, "Faster raw, tail cut edits."],
  ["Radical Redemption", "Brutal 3.0", 2017, 152, "Distortion as the melody."],
  ["Radical Redemption", "Nothing to Fear", 2015, 150, "Dark vocal break, heavy drop."],
  ["Phuture Noize", "Fire", 2016, 155, "Melodic raw with screech doubling."],
  ["Adaro", "Ace of Spades", 2014, 150, "Raw groove, sample hook."],
  ["Digital Punk", "Unleashed", 2013, 150, "Punchy, distorted, screech riff."],
  ["Crypsis", "Bring This Down", 2014, 150, "Gritty tail, movie sample."],
  ["Minus Militia", "Mayhem", 2015, 152, "Supergroup raw: stacked screeches."],
  ["Delete", "Rise", 2015, 152, "Warped screech, kick variations."],
  ["Warface & Delete", "The Illusion", 2016, 152, "Long distorted tail, kick rolls."],
  ["Rebelion", "Not Human", 2016, 152, "Dark stabs, wobble screech."],
  ["Rebelion", "World of Pain", 2017, 155, "Extra grit in the low-mids."],
  ["Regain", "Faded Memories", 2016, 152, "Raw kick under a melodic riff."],
  ["Adjuzt", "Bring It Back", 2018, 155, "Modern raw kick design."],
  ["Chain Reaction", "Answers", 2013, 150, "Sample intro, mid-heavy drop."],
  ["Titan", "Toxic", 2014, 150, "Screech riff over a gritty kick."],
  ["Frequencerz", "Fckin Sick", 2014, 150, "Shout hook, hard kick edits."],
  ["Digital Punk & Profyler", "Death Row", 2014, 150, "Movie sample, distorted tail."],
  ["Ran-D & B-Front", "Break the Line", 2015, 152, "Pitch-bent kick variations."],
  ["Warface", "Voices of Hell", 2017, 155, "Wobble screech, heavy mids."],
  ["Radical Redemption & Warface", "Blood & Bones", 2018, 155, "Collab raw: kick swaps every 8."],
  ["B-Front", "Spectrum", 2017, 155, "Raw kick with melodic answer."],
  ["Killshot", "Bad Habit", 2018, 158, "Late raw pushing toward xtra."],
  ["Malice", "Rise to Power", 2018, 158, "Screech stack, siren build."],
  ["Deadly Guns", "Rebirth", 2015, 155, "Raw/hardcore crossover kick."],
  ["Rooler", "Hurt", 2019, 158, "Modern raw tail, minimal harmony."],
  ["Level One", "Beast Mode", 2019, 158, "Distorted mids, roll transitions."],
  ["Riot Shift", "The Pursuit", 2018, 158, "Dark kick, screech rhythm."],
  ["Vasto", "Riot", 2019, 158, "Punch-tok-tail at full distortion."],
  ["Sub Sonik", "Riot", 2017, 155, "Kick rolls, wobble screech."],
  ["Warface & Sub Sonik", "Cruel Intentions", 2017, 155, "Collab raw, alternating kicks."],
  ["Digital Punk", "The Return", 2016, 152, "Classic raw kick redesign."],
  ["E-Force", "Nightmare", 2015, 152, "Screech hook, dark pad break."],
  ["Adaro", "Feel My Presence", 2016, 152, "Sample hook, gritty tail."],
  ["Crypsis", "Sharp Sound", 2016, 152, "Distortion-heavy drop."],
  ["Delete", "Deleted", 2017, 155, "Wobble screech, hard rolls."],
  ["Gunz for Hire", "Kings of the Underground", 2016, 152, "Anthemic raw, vocal sample."],
];

const XTRA_RAW: Row[] = [
  ["Sub Sonik", "Rewind", 2018, 160, "Speed and grit; screech stack."],
  ["Killshot", "Ultimate Bass Test", 2018, 160, "Sub + distorted layer alternate."],
  ["Killshot & Mutilator", "Unstoppable", 2019, 162, "Kick edits every 2 bars."],
  ["Mutilator", "The Bringer of Death", 2019, 162, "Long, dirty tail; siren build."],
  ["Malice", "Wrath of the Beast", 2019, 160, "Screech wobble, industrial noise."],
  ["Riot Shift", "Faded", 2019, 160, "Dark xtra raw, tail cuts."],
  ["Level One", "Nightmares", 2019, 160, "Roll-heavy drop."],
  ["Chapter V", "Ravers Paradise", 2019, 160, "Sample hook, kick stutters."],
  ["Vasto", "Hard Wired", 2020, 162, "Metallic mids, pitch-up rolls."],
  ["Rooler", "Overkill", 2020, 162, "Two kicks alternating, screech percussion."],
  ["Warface", "Cheat Codes", 2019, 158, "Harder Warface, roll transitions."],
  ["Sub Sonik & Delete", "Rise Up", 2019, 160, "Wobble screech, reverse kick edits."],
  ["Killshot", "Freakshow", 2020, 162, "Sub-heavy roll kick."],
  ["Mutilator", "Bad Blood", 2020, 162, "Grit in 300–800 Hz."],
  ["Malice & Rebelion", "Fear No More", 2020, 160, "Stacked screeches, siren build."],
  ["Rooler & Sickmode", "Get Down", 2021, 165, "Uptempo-flavoured xtra raw rolls."],
  ["Sickmode", "Wanna Play", 2021, 165, "Screech as the hook, brutal tail."],
  ["Vasto & Rooler", "Freakz", 2021, 162, "Kick swaps every 4 bars."],
  ["Level One", "Bass Cannon", 2020, 160, "Long distorted tail, minimal harmony."],
  ["Riot Shift", "Silence", 2020, 160, "Dark break, screech stack drop."],
  ["Chapter V", "Hostile", 2020, 160, "Noise texture break, roll build."],
  ["Killshot", "Nowhere to Run", 2021, 162, "Modern xtra raw kick design."],
  ["Mutilator & Malice", "Mayhem", 2021, 162, "Collab: alternating kicks and screeches."],
  ["Sub Sonik", "Blaze", 2020, 160, "Pitch-bent screech riff."],
  ["Warface & Rooler", "No Escape", 2021, 160, "Metallic tail, hard edits."],
  ["Delete", "Warzone", 2020, 160, "Wobble screech, industrial FX."],
  ["Sickmode & Rooler", "Mad", 2022, 165, "Extreme kick rolls, shout samples."],
  ["Vasto", "Villain", 2022, 162, "Dirty tail with a clean punch layer."],
  ["Chapter V & Level One", "Rampage", 2021, 160, "Roll build into a screech drop."],
  ["Riot Shift & Vasto", "Rebellion", 2022, 162, "Two-kick alternation."],
  ["Killshot", "Deadline", 2022, 162, "Tail cut edits, siren build."],
  ["Mutilator", "Destroyer", 2022, 162, "Longest tails in the lane."],
  ["Malice", "Bring the Fire", 2022, 160, "Screech stack, shout hook."],
  ["Sub Sonik", "Riot Squad", 2021, 160, "Kick edits as transitions."],
  ["Rooler", "Trauma", 2022, 165, "Uptempo-style rolls at 165."],
  ["Sickmode", "Mind Games", 2022, 165, "Pitch-up kick rolls, screech percussion."],
  ["Level One", "Unholy", 2022, 162, "Industrial noise break."],
  ["Chapter V", "Purgatory", 2022, 162, "Reverse-kick edits, wobble screech."],
  ["Warface", "Grim", 2022, 160, "Metallic mids, siren."],
  ["Vasto", "Insane", 2023, 162, "Sub punch + distorted roll kick."],
  ["Killshot & Riot Shift", "No Mercy", 2023, 162, "Stacked screeches."],
  ["Mutilator", "Executioner", 2023, 162, "Grit-first kick design."],
  ["Malice", "Dominion", 2023, 160, "Shout samples, tail cuts."],
  ["Sickmode", "Hostile", 2023, 165, "Fastest rolls in the lane."],
  ["Rooler", "Reckless", 2023, 165, "Two kicks, screech rhythm."],
  ["Sub Sonik", "Unleash", 2023, 160, "Modern xtra raw master."],
  ["Level One", "Savage", 2023, 162, "Roll transitions every 2 bars."],
  ["Chapter V", "Doom", 2023, 162, "Noise textures, siren build."],
  ["Riot Shift", "Chaos", 2023, 162, "Dark, minimal, brutal."],
  ["Vasto & Sickmode", "Ruthless", 2024, 165, "Kick as the only instrument."],
];

const RAWPHORIC: Row[] = [
  ["Phuture Noize", "Warped Utopia", 2016, 155, "Melodic break, raw kick drop."],
  ["Phuture Noize", "Fire", 2016, 155, "Screech doubling the melody."],
  ["B-Front", "Dark Waves", 2016, 152, "Emotional chords over a heavy kick."],
  ["Rebelion", "Grave Digger", 2017, 155, "Melodic drop then raw drop."],
  ["Aftershock", "Endless", 2017, 155, "Layered lead, distorted tail."],
  ["Regain", "The Way Home", 2017, 155, "Piano break into raw kick."],
  ["Adjuzt", "Colors of the Night", 2018, 155, "Vocal chops + raw kick."],
  ["Warface", "Warriors", 2017, 155, "Anthemic melody, gritty kick."],
  ["Sub Sonik", "Faded", 2018, 155, "Softer Sub Sonik: chords + raw tail."],
  ["Devin Wild", "The Sunrise", 2017, 155, "Melodic raw build."],
  ["Vertile", "Fake Names", 2019, 155, "Vocal-led rawphoric."],
  ["Phuture Noize", "Black Symphony", 2018, 155, "Orchestral break, raw drop."],
  ["B-Front & Phuture Noize", "Only Us", 2019, 155, "Two lanes in one track."],
  ["Rebelion", "The Underground", 2018, 155, "Raw stabs, melodic answer."],
  ["Aftershock", "Rise", 2018, 155, "Melody in the drop, kick edits."],
  ["Regain", "Lost", 2018, 155, "Euphoric lead, raw kick."],
  ["Adjuzt", "Reflections", 2019, 155, "Wide lead, controlled tail."],
  ["Warface", "Nuclear", 2018, 155, "Melodic raw at full loudness."],
  ["Phuture Noize", "The Universe", 2020, 155, "Long cinematic break."],
  ["B-Front", "Tonight", 2018, 155, "Vocal hook, gritty drop."],
  ["Sub Sonik", "Colors", 2019, 155, "Lead + screech pairing."],
  ["Devin Wild", "Home", 2019, 155, "Sung vocal, raw kick."],
  ["Vertile", "Hurt", 2020, 155, "Emotional rawphoric."],
  ["Rebelion", "Pray", 2019, 155, "Choir break into raw drop."],
  ["Aftershock", "Feel Alive", 2019, 155, "Bright lead on a raw tail."],
  ["Regain", "Awake", 2019, 155, "Pluck lead + raw kick."],
  ["Adjuzt", "Chasing", 2020, 155, "Chords change inside the drop."],
  ["Phuture Noize & Sub Sonik", "Clash", 2019, 155, "Melodic then raw drop."],
  ["B-Front", "Follow Your Heart", 2020, 155, "Sung hook, screech answer."],
  ["Warface", "Lost", 2020, 155, "Melodic raw, kick swaps."],
  ["Sub Sonik", "Home", 2020, 155, "Vocal + raw tail."],
  ["Devin Wild", "Wild Things", 2020, 155, "Playful lead, raw kick."],
  ["Vertile", "Breathe", 2021, 155, "Modern rawphoric master."],
  ["Rebelion", "Legacy", 2020, 155, "Anthemic raw."],
  ["Aftershock", "Believe", 2020, 155, "Chords + screech."],
  ["Regain", "Symphony", 2020, 155, "Orchestral rawphoric."],
  ["Adjuzt", "Gravity", 2021, 155, "Wide lead, clean sub."],
  ["Phuture Noize", "Dreams", 2021, 155, "Emotional vocal, raw drop."],
  ["B-Front", "Rise Again", 2021, 155, "Melody answered by screech."],
  ["Warface", "Reborn", 2021, 155, "Melodic raw at 155."],
  ["Sub Sonik", "Tonight", 2021, 155, "Pop hook + raw kick."],
  ["Devin Wild", "Sky", 2021, 155, "Bright, wide, gritty."],
  ["Vertile", "Believe", 2022, 155, "Layered lead, raw tail."],
  ["Rebelion", "Fire", 2022, 155, "Raw stabs + melody."],
  ["Aftershock", "Rise Again", 2022, 155, "Cinematic break."],
  ["Regain", "Free", 2022, 155, "Vocal chops, raw kick."],
  ["Adjuzt", "Home", 2022, 155, "Sung vocal, screech layer."],
  ["Phuture Noize", "Legacy", 2022, 155, "Long break, huge drop."],
  ["B-Front", "Eternity", 2023, 155, "Melodic raw anthem."],
  ["Warface", "Unity", 2023, 155, "Rawphoric festival master."],
];

const PSY: Row[] = [
  ["Sub Zero Project", "The Project", 2016, 150, "Rolling psy bass under a hardstyle kick."],
  ["Sub Zero Project", "The Contact", 2017, 150, "Acid line hook, short kick."],
  ["Sub Zero Project", "DRKNSS", 2017, 150, "Dark psy build, tribal break."],
  ["Sub Zero Project & Coone", "Tha Bounce", 2017, 150, "Bounce meets psy bass."],
  ["Sub Zero Project", "Rave Into Space", 2019, 150, "Space FX, filter-opening build."],
  ["Sub Zero Project", "Our Church", 2019, 150, "Modal lead, hypnotic bass."],
  ["Sub Zero Project", "Symphony of Sins", 2019, 150, "Orchestral psystyle anthem."],
  ["Wasted Penguinz", "Rise Above", 2018, 150, "Psy influences on a melodic base."],
  ["Zatox", "Peace of Mind", 2017, 150, "Zatox psy: 16th bass, acid sweeps."],
  ["Mandy", "Nightfall", 2018, 150, "Rolling bass, zap FX."],
  ["Sound Rush", "Psycho", 2018, 150, "Sound Rush's psy lane."],
  ["Keltek", "Dynamics", 2018, 150, "Acid resonance, short kick."],
  ["Vertile", "Lost in Space", 2019, 150, "Psy FX over a melodic lead."],
  ["Toneshifterz", "Psy Trip", 2018, 150, "Tribal samples, 303 line."],
  ["Code Black", "Hypnotic", 2018, 150, "Filter sweep build."],
  ["Adrenalize", "Voyage", 2018, 150, "Rolling bass, airy pluck."],
  ["Sub Zero Project", "Nemesis", 2020, 150, "Dark psy build, heavy drop."],
  ["Sub Zero Project", "Genesis", 2020, 150, "Cinematic psy anthem."],
  ["Zatox", "Ultimate", 2018, 150, "Acid lead, tight kick."],
  ["Mandy", "Illusions", 2019, 150, "Modal melody, psy bass."],
  ["Sound Rush", "Trip", 2019, 150, "Rolling groove, zaps."],
  ["Keltek", "Odyssey", 2019, 150, "Psy plucks, 16th bass."],
  ["Vertile", "Awake", 2020, 150, "Psy-flavoured euphoric."],
  ["Toneshifterz", "Ritual", 2019, 150, "Ethnic chant, acid line."],
  ["Code Black", "Trance Mission", 2019, 150, "Trance chords + psy bass."],
  ["Adrenalize", "Escape", 2019, 150, "Hypnotic build, resonant lead."],
  ["Sub Zero Project", "Neon", 2021, 150, "Modern psystyle master."],
  ["Zatox", "Dimension", 2019, 150, "Space FX break."],
  ["Mandy", "Tribe", 2020, 150, "Tribal percussion, 303."],
  ["Sound Rush", "Mystic", 2020, 150, "Modal lead, rolling bass."],
  ["Keltek", "Portal", 2020, 150, "Zap FX, filter build."],
  ["Vertile", "Spectrum", 2021, 150, "Wide psy lead."],
  ["Toneshifterz", "Shaman", 2020, 150, "Chant hook, acid answer."],
  ["Code Black", "Vortex", 2020, 150, "Rolling bass at full loudness."],
  ["Adrenalize", "Orbit", 2020, 150, "Airy pluck, short kick."],
  ["Sub Zero Project", "Zero Gravity", 2021, 150, "Space break, psy drop."],
  ["Zatox", "Resonance", 2020, 150, "Resonant filter as the hook."],
  ["Mandy", "Ascend", 2021, 150, "Modal, hypnotic, driving."],
  ["Sound Rush", "Signal", 2021, 150, "Zaps, sweeps, rolling groove."],
  ["Keltek", "Infinity", 2021, 150, "Acid lead over tribal drums."],
  ["Vertile", "Mirage", 2022, 150, "Psy FX + vocal chops."],
  ["Toneshifterz", "Totem", 2021, 150, "Ethnic sample, 16th bass."],
  ["Code Black", "Eclipse", 2021, 150, "Trance break, psy drop."],
  ["Adrenalize", "Gravity", 2021, 150, "Filter-opening build."],
  ["Sub Zero Project", "Ascension", 2022, 150, "Anthemic psystyle."],
  ["Zatox", "Odyssey", 2021, 150, "Acid + hardstyle kick."],
  ["Mandy", "Vision", 2022, 150, "Modal pluck, rolling bass."],
  ["Sound Rush", "Pulse", 2022, 150, "Tight kick, 16th groove."],
  ["Keltek", "Nova", 2022, 150, "Space FX, resonant lead."],
  ["Vertile", "Horizon", 2023, 150, "Modern psy-euphoric hybrid."],
];

const HARDCORE: Row[] = [
  ["Angerfist", "Raise Your Fist", 2007, 175, "Mainstream hardcore blueprint."],
  ["Angerfist", "Incoming", 2008, 175, "Distorted kick + hoover."],
  ["Angerfist", "Dance With the Wolves", 2010, 175, "Melodic break, brutal drop."],
  ["Angerfist", "The Deadfaced Dimension", 2014, 175, "Album-era polished hardcore."],
  ["Angerfist & Miss K8", "Bloodlust", 2013, 175, "Collab: screech riff, heavy kick."],
  ["Miss K8", "Unforgettable", 2013, 175, "Melodic hardcore anthem."],
  ["Miss K8", "Raiders of Rampage", 2015, 175, "Kick harmonics carry the mids."],
  ["Tha Playah", "Menace II Society", 2011, 175, "Movie sample, hoover chords."],
  ["Tha Playah", "Ain't Nothing But a Hardcore Party", 2009, 175, "Party hardcore, shout hook."],
  ["Evil Activities", "Nobody Said It Was Easy", 2010, 175, "Vocal cover, mainstream break."],
  ["Evil Activities", "World of Madness", 2012, 175, "Defqon anthem energy at 175."],
  ["Nosferatu", "Gates of Oblivion", 2012, 175, "Darker mainstream, screech lead."],
  ["Nosferatu", "When Angels Cry", 2009, 175, "Melodic break, distorted drop."],
  ["Neophyte", "Braincracking", 1995, 180, "Old-school foundation."],
  ["Neophyte & Evil Activities", "Alles Kapot", 2012, 175, "Dutch shout hook."],
  ["N-Vitral", "Bass Cannon", 2013, 175, "Kick as sub + lead."],
  ["N-Vitral", "Crispy Bassdrum", 2015, 175, "Kick design showcase."],
  ["Mad Dog", "Agony", 2010, 175, "Dark mainstream hardcore."],
  ["Mad Dog", "The Night of Darkness", 2012, 175, "Orchestral break."],
  ["Korsakoff", "Stardust", 2012, 175, "Female vocal, melodic hardcore."],
  ["Korsakoff", "Skydiver", 2013, 175, "Bright break, hard drop."],
  ["Destructive Tendencies", "Hardcore Machine", 2015, 180, "Roll-heavy mainstream."],
  ["Art of Fighters", "Toxic Hotel", 2012, 175, "Italian hardcore, vocal hook."],
  ["Endymion", "Anarchy", 2013, 175, "Anthemic mainstream."],
  ["The Outside Agency", "Scoop Some Bastard", 2010, 180, "Industrial edge."],
  ["Dyprax", "The Hallway", 2013, 175, "Pitched screech, heavy kick."],
  ["Outblast", "Master of Creation", 2007, 175, "Masters of Hardcore anthem style."],
  ["Promo", "The Worst Is Yet to Come", 2012, 175, "Millennium hardcore edge."],
  ["Furyan", "Lost Souls", 2013, 175, "Dark melodic hardcore."],
  ["Re-Style", "Ultimate Pain", 2013, 175, "Emotional break, distorted drop."],
  ["Unexist", "Fuck the Speakers", 2009, 175, "Speaker-testing kick."],
  ["Rotterdam Terror Corps", "Hardcore Now", 2010, 180, "RTC party hardcore."],
  ["Bodyshock", "Suicide Mind", 2014, 175, "Dark, industrial-tinged."],
  ["Deadly Guns", "Legends", 2016, 180, "Crossover to uptempo."],
  ["Miss K8", "Temper", 2016, 175, "Kick edits + screech."],
  ["Angerfist", "Bite Yo Style", 2011, 175, "Shout hook, hoover."],
  ["Angerfist", "Take U Back", 2013, 175, "Vocal cover, big break."],
  ["Tha Playah", "Say Your Prayers", 2015, 175, "Movie sample hook."],
  ["N-Vitral", "Wreckage", 2017, 180, "Crunchy kick, roll build."],
  ["Nosferatu", "Legends Never Die", 2014, 175, "Anthemic melody."],
  ["Mad Dog", "Payback", 2015, 175, "Dark stabs, kick as bass."],
  ["Korsakoff", "Zombies", 2014, 175, "Vocal hook, heavy drop."],
  ["Evil Activities", "Extreme Audio", 2008, 175, "Aggressive sample hook."],
  ["Destructive Tendencies", "Shockwave", 2016, 180, "Fast mainstream hardcore."],
  ["Dyprax", "Bloody Rave", 2014, 175, "Rave stabs, distorted kick."],
  ["Endymion", "Strike Back", 2015, 175, "Big melody, hard kick."],
  ["Art of Fighters", "Artillery", 2014, 175, "Italian kick punch."],
  ["Furyan", "Devil's Game", 2016, 175, "Dark hardcore master."],
  ["Re-Style", "Never Give Up", 2016, 175, "Melodic hardcore anthem."],
  ["Outblast", "Rebirth", 2011, 175, "Classic MoH energy."],
];

const UPTEMPO: Row[] = [
  ["Partyraiser & Destructive Tendencies", "Sound Becomes One", 2016, 190, "Roll transitions, sub-heavy kick."],
  ["Partyraiser", "This Is Uptempo", 2017, 200, "Lane-defining roll patterns."],
  ["Dr. Peacock & Partyraiser", "Kick It Hard", 2017, 200, "Frenchcore meets uptempo."],
  ["Sjammienators", "Kick Nation", 2017, 200, "Kick-only drops."],
  ["Spitnoise", "Uptempo Rebel", 2017, 200, "Screech + rolls."],
  ["F.Noize", "Bring the Noize", 2017, 200, "Shout sample, triplet rolls."],
  ["Barber", "Uptempo Warrior", 2018, 210, "Fast rolls, sirens."],
  ["Deadly Guns", "Bad Ass", 2017, 200, "Sub punch + distorted roll kick."],
  ["Bloodlust", "Destruction", 2018, 210, "Tempo changes mid-track."],
  ["Soulblast", "Rage", 2019, 210, "Chopped vocals, rolls."],
  ["The Dark Horror", "Chaos", 2019, 210, "Extreme rolls, siren build."],
  ["Partyraiser & Bulletproof", "The Underground", 2018, 200, "Roll drop, short sections."],
  ["Sjammienators", "Uptempo Is the Tempo", 2018, 210, "Anthem for the movement."],
  ["Spitnoise", "Fuck You", 2018, 210, "Meme sample, brutal rolls."],
  ["F.Noize", "Bass Cannon", 2018, 210, "Sub sine under distorted rolls."],
  ["Barber", "Fast as Fuck", 2019, 220, "230 BPM sections."],
  ["Deadly Guns", "The Enemy", 2018, 200, "Melodic break, roll drop."],
  ["Bloodlust", "Uptempo Army", 2019, 210, "Shout hook, kick rolls."],
  ["Soulblast", "Revolt", 2020, 210, "Screech percussion, rolls."],
  ["The Dark Horror", "Terror", 2020, 220, "Fastest rolls in the lane."],
  ["Partyraiser", "Fuck the Pussies", 2019, 200, "Sample-led uptempo."],
  ["Sjammienators", "Sjammie Nation", 2019, 210, "Roll patterns as melody."],
  ["Spitnoise", "Rebel", 2019, 210, "Vocal chops, sirens."],
  ["F.Noize", "Noize Attack", 2019, 210, "Triplet rolls, screech."],
  ["Barber", "Uptempo Madness", 2020, 220, "Tempo jumps."],
  ["Deadly Guns", "Wheels of Steel", 2019, 200, "Crossover anthem."],
  ["Bloodlust", "Bloodlust", 2020, 210, "Signature roll drop."],
  ["Soulblast", "Insanity", 2021, 210, "Chopped vocal hook."],
  ["The Dark Horror", "Nightmare", 2021, 220, "Extreme uptempo master."],
  ["Partyraiser", "Roughest & Toughest", 2020, 200, "Shout hook, rolls."],
  ["Sjammienators", "Kick Rolls", 2020, 210, "Roll showcase."],
  ["Spitnoise", "Hardcore Rebel", 2020, 210, "Screech + rolls + sample."],
  ["F.Noize", "Uptempo Anthem", 2020, 210, "Anthemic break, roll drop."],
  ["Barber", "Faster", 2021, 220, "220+ BPM rolls."],
  ["Deadly Guns", "Legends 2", 2020, 200, "Melodic uptempo."],
  ["Bloodlust", "Riot", 2021, 210, "Siren build, rolls."],
  ["Soulblast", "Chaos", 2022, 210, "Sub-heavy roll kick."],
  ["The Dark Horror", "Destruction", 2022, 220, "Tempo change drops."],
  ["Partyraiser", "Uptempo Party", 2021, 200, "Party uptempo."],
  ["Sjammienators", "Roll With It", 2021, 210, "Roll transitions every 2 bars."],
  ["Spitnoise", "Spit Fire", 2021, 210, "Screech hook."],
  ["F.Noize", "Bring It", 2021, 210, "Triplet + 32nd rolls."],
  ["Barber", "Uptempo Boss", 2022, 220, "Fastest master in the lane."],
  ["Deadly Guns", "Rebirth 2", 2021, 200, "Melodic break, roll drop."],
  ["Bloodlust", "War", 2022, 210, "Shout samples, rolls."],
  ["Soulblast", "Fury", 2023, 210, "Modern uptempo master."],
  ["The Dark Horror", "Chaos 2", 2023, 220, "Extreme rolls, sirens."],
  ["Partyraiser", "Still Raising", 2022, 200, "Roll drop anthem."],
  ["Sjammienators", "Tempo", 2022, 210, "Kick-only drop."],
  ["Spitnoise", "Uptempo Life", 2023, 210, "Vocal chop hook."],
];

const FRENCHCORE: Row[] = [
  ["Dr. Peacock", "Trip to Poland", 2013, 200, "The 'Trip to' template: folk melody + bounce."],
  ["Dr. Peacock", "Trip to Russia", 2014, 200, "Anthemic break, bounce drop."],
  ["Dr. Peacock", "Trip to Ireland", 2015, 200, "Folk lead, off-beat bass."],
  ["Dr. Peacock", "Trip to Italy", 2015, 200, "Accordion-style melody."],
  ["Dr. Peacock", "Vive la Frenchcore", 2015, 200, "Lane anthem; bounce at full loudness."],
  ["Dr. Peacock", "Trip to Britain", 2016, 200, "Sing-along break."],
  ["Dr. Peacock", "Trip to Spain", 2016, 200, "Guitar-flavoured lead."],
  ["Dr. Peacock", "Trip to Germany", 2017, 200, "Big-room bounce."],
  ["Dr. Peacock & Sefa", "Bulletproof", 2017, 200, "Collab: melodic frenchcore."],
  ["Sefa", "Leven Is Lijden", 2017, 200, "Dutch vocal hook, emotional break."],
  ["Sefa", "Memento", 2018, 200, "Cinematic frenchcore."],
  ["The Sickest Squad", "Skattatak", 2014, 200, "Italian frenchcore, playful lead."],
  ["Radium", "Ich Bin Hardcore", 2010, 200, "Old-school French kick."],
  ["Maissouille", "Bombe", 2012, 200, "Hard French bounce."],
  ["Hyrule War", "The Legend", 2016, 200, "Game-melody frenchcore."],
  ["Mr. Ivex", "Ready to Rock", 2016, 200, "Party frenchcore."],
  ["Remzcore", "Rock the Bass", 2017, 200, "Bounce-driven."],
  ["Pattern J", "Shine", 2018, 200, "Melodic, bright."],
  ["Billx", "Frenchcore Family", 2017, 200, "Family anthem."],
  ["Dr. Peacock", "Trip to Belgium", 2018, 200, "Bounce with a pitched vocal."],
  ["Sefa", "Yin Yang", 2018, 200, "Two-part structure."],
  ["Dr. Peacock & Sefa", "Ambush", 2018, 200, "Kick tuned to the bounce."],
  ["The Sickest Squad", "Manifesto", 2016, 200, "Sing-along frenchcore."],
  ["Radium", "Speedcore Rocker", 2012, 200, "Faster French edge."],
  ["Maissouille", "Reflexion", 2015, 200, "Melodic French bounce."],
  ["Hyrule War", "Quest", 2018, 200, "Chiptune melody, bounce."],
  ["Mr. Ivex", "Rockstar", 2018, 200, "Shout hook, bounce."],
  ["Remzcore", "Fire", 2019, 200, "Rolling bounce drop."],
  ["Pattern J", "Ascend", 2019, 200, "Uplifting frenchcore."],
  ["Billx", "Rise", 2019, 200, "Big melodic break."],
  ["Dr. Peacock", "Trip to Australia", 2019, 200, "Bounce + vocal hook."],
  ["Sefa", "Solitude", 2019, 200, "Emotional break, bounce drop."],
  ["Dr. Peacock & Sefa", "Bounce", 2019, 200, "Bounce showcase."],
  ["The Sickest Squad", "Rocket Trip", 2018, 200, "Playful lead."],
  ["Radium", "French Connection", 2015, 200, "Old-school French."],
  ["Maissouille", "Vengeance", 2018, 200, "Hard bounce."],
  ["Hyrule War", "Hero", 2020, 200, "Game melody + bounce."],
  ["Mr. Ivex", "Rebel", 2020, 200, "Party bounce."],
  ["Remzcore", "Frenchcore Life", 2020, 200, "Lane anthem style."],
  ["Pattern J", "Dream", 2020, 200, "Melodic bounce."],
  ["Billx", "Home", 2020, 200, "Vocal hook, bounce drop."],
  ["Dr. Peacock", "Trip to Scotland", 2020, 200, "Folk lead, bagpipe motif."],
  ["Sefa", "Alive", 2020, 200, "Sung vocal, bounce."],
  ["Dr. Peacock & Sefa", "Legends", 2021, 200, "Anthemic collab."],
  ["The Sickest Squad", "Crazy", 2020, 200, "Playful hook."],
  ["Radium", "Hardcore Vibes", 2018, 200, "French kick, bounce."],
  ["Maissouille", "Domination", 2020, 200, "Hard French bounce."],
  ["Hyrule War", "Zelda", 2021, 200, "Game melody frenchcore."],
  ["Mr. Ivex", "Rock It", 2021, 200, "Bounce, shout hook."],
  ["Billx", "Together", 2021, 200, "Sing-along frenchcore."],
];

export const HH_REFS: RefTrack[] = [
  ...lane("early", EARLY),
  ...lane("classic", CLASSIC),
  ...lane("euphoric", EUPHORIC),
  ...lane("raw", RAW),
  ...lane("xtra-raw", XTRA_RAW),
  ...lane("rawphoric", RAWPHORIC),
  ...lane("psy", PSY),
  ...lane("hardcore", HARDCORE),
  ...lane("uptempo", UPTEMPO),
  ...lane("frenchcore", FRENCHCORE),
];

export function refsFor(genre: HhGenreId): RefTrack[] {
  return HH_REFS.filter((r) => r.genre === genre);
}

/** Closest references by tempo inside one lane. */
export function closestRefs(genre: HhGenreId, bpm: number, n = 6): RefTrack[] {
  return [...refsFor(genre)].sort((a, b) => Math.abs(a.bpm - bpm) - Math.abs(b.bpm - bpm)).slice(0, n);
}
